DELETE FROM acomodo;

DELETE FROM material_master;

DELETE FROM avion_sistema_entretenimiento;

DELETE FROM proveedor_estacion;

DELETE FROM avion_capacidad;

DELETE FROM relacion_flota;

DELETE FROM equipamiento_comisariato;

DELETE FROM perfil_usuario;

DELETE FROM avion_audifono;

DELETE FROM horario;

DELETE FROM vuelo;

DELETE FROM matriz_detalle;

DELETE FROM contacto_proveedor_estacion;

DELETE FROM codigo_servicio;

DELETE FROM empleado;

DELETE FROM grafico_detalle;

DELETE FROM modulo_perfil;

DELETE FROM traduccion;

DELETE FROM matriz;

DELETE FROM area;

DELETE FROM acomodo_detalle;

DELETE FROM grafico;

DELETE FROM sistema_entretenimiento;

DELETE FROM proveedor;

DELETE FROM perfil;

DELETE FROM tipo_proveedor;

DELETE FROM clase;

DELETE FROM usuario;

DELETE FROM material;

DELETE FROM avion;

DELETE FROM kit_master;

DELETE FROM categoria_material;

DELETE FROM producto;

DELETE FROM estacion;

DELETE FROM ciudad;

DELETE FROM pais;

DELETE FROM region;

DELETE FROM tipo_equipo_avion;

DELETE FROM modelo_avion;

DELETE FROM compania;

DELETE FROM parametros;

