-- ============================= ELIMINADO DEL ESQUEMA DE LA BASE DE DATOS ====================
-- ===================================== TABLES (90) ===============================
DROP TABLE equipamiento_semifijo;

DROP TABLE relacion_flota;

DROP TABLE comunicado_proveedor_estacion;

DROP TABLE Kit_TSU;

DROP TABLE acomodo_producto;

DROP TABLE auditable;

DROP TABLE detalle_modelo_abordaje;

DROP TABLE configuracion_reporte;

DROP TABLE material_extra;

DROP TABLE cantidad_vuelo_complementario;

DROP TABLE avion_audifono;

DROP TABLE grafico_detalle;

DROP TABLE responsable_producto;

DROP TABLE perfil_usuario;

DROP TABLE Configuracion_Ciclo;

DROP TABLE pax_compementario;

DROP TABLE traduccion;

DROP TABLE opcion_menu_perfil;

DROP TABLE evidencia;

DROP TABLE grafico_producto;

DROP TABLE proveedor_region;

DROP TABLE archivo;

DROP TABLE Material_TSU;

DROP TABLE potencial;

DROP TABLE horario;

DROP TABLE action_form;

DROP TABLE equipamiento_fijo;

DROP TABLE configuracion_reporte_detalle;

DROP TABLE matriz_detalle;

DROP TABLE comunicado_areas;

DROP TABLE bitacora_comunicado;

DROP TABLE Asignacion_Servicio_Duracion;

DROP TABLE proveedor_estacion_tipo_proveedor;

DROP TABLE tsu_ciclo;

DROP TABLE ciclo_complementario;

DROP TABLE avion_sistema_entretenimiento;

DROP TABLE avion_capacidad;

DROP TABLE sobreabordaje;

DROP TABLE region_abordaje_estacion;

DROP TABLE material_kit_master;

DROP TABLE region_abordaje;

DROP TABLE Asignacion_Servicio;

DROP TABLE sistema_entretenimiento;

DROP TABLE Duracion_vuelos;

DROP TABLE matriz;

DROP TABLE detalle_tabla_tsu;

DROP TABLE Horario_Region;

DROP TABLE acomodo;

DROP TABLE Proceso;

DROP TABLE tipo_proveedor;

DROP TABLE ciclo;

DROP TABLE seguimiento;

DROP TABLE opcion_menu;

DROP TABLE acomodo_detalle;

DROP TABLE tipo_irregularidad;

DROP TABLE tsu_abordamiento;

DROP TABLE perfil;

DROP TABLE criterio_irregularidad;

DROP TABLE grafico;

DROP TABLE contacto_proveedor_estacion;

DROP TABLE Comunicado;

DROP TABLE reporte;

DROP TABLE detalle_tabla_complementario;

DROP TABLE tema_comunicado;

DROP TABLE producto;

DROP TABLE kit_master;

DROP TABLE vuelo;

DROP TABLE avion;

DROP TABLE TSU;

DROP TABLE tipo_equipo_avion;

DROP TABLE tipo_producto_reporte;

DROP TABLE responsable_estacion;

DROP TABLE Material;

DROP TABLE categoria_material;

DROP TABLE empleado;

DROP TABLE tabla_abordamiento;

DROP TABLE proveedor_estacion;

DROP TABLE multimedio;

DROP TABLE Codigo_Servicio;

DROP TABLE usuario;

DROP TABLE modelo_avion;

DROP TABLE proveedor;

DROP TABLE area;

DROP TABLE Compania;

DROP TABLE clase;

DROP TABLE estacion;

DROP TABLE ciudad;

DROP TABLE pais;

DROP TABLE region;

DROP TABLE parametro;

